baseURL = 'https://github.io'
canonifyURLs = true
title = 'Ngulik Tech'
theme ='congo'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  colorScheme="avocado"
  defaultAppearance="dark"
  autoSwitchAppearance=true
[params.homepage]
  layout="profile"
  showRecent=true
[params.author]
  name="Candra Wirawan"
  image = '/images/profil.png'
  headline = 'Hello World'
  links = [
    {github="https://github.com/wirawancandra631"},
    {instagram="https://www.instagram.com/w_candra99/"},
    {linkedin="www.linkedin.com/in/candra-wirawan-2bb85430a"},
  ]
[params.footer]
 showAppearanceSwitcher=true
[params.article]

